#define RED 0
#define GREEN 1
#define BLUE 2

#define SCREEN_HEIGHT 1024
#define SCREEN_WIDTH 1024
#define CHANNEL 3

#define CORRECTION_GAMMA 1
#define ANTIALIASING 1
#define ROULETTE 0
#define FRESNEL 0
#define CAMERA_MODEL 0
#define MOTION_BLUR 0
#define PHONG 0
#define ATMOSPHERE 0

#define RECURSION_LEVEL 3
#define RECURSION_BOXES 30
#define MONTE_CARLO_N 5

#define EPSILON 0.1
#define GAMMA 2.2
#define N_AIR 1
#define ROULETTE_THRESHOLD 0.9
#define CAMERA_FIELD 5
#define TIME_STEPS 1
#define PROBABILITE_UNIFORME 0.25
